name: Azure build
permissions:
  id-token: write
  
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # ubuntu Az CLI installation -  based on https://github.com/Azure/login#sample-workflow-that-uses-azure-login-action-using-oidc-to-run-az-cli-linux
    - name: Install CLI-beta
      run: |
         cd ../..
         CWD="$(pwd)"
         python3 -m venv oidc-venv
         . oidc-venv/bin/activate
         echo "activated environment" 
         python3 -m pip install --upgrade pip
         echo "started installing cli beta" 
         pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
         echo "installed cli beta"    
         echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH   

    - name: 'Az CLI login'
      uses: azure/login@v1.4.0
      with:
        client-id: ${{ secrets.AZURE_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_TENANTID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

    - name: 'Run az commands'
      run: |
        az account show
        az group list
        pwd 
        
  #  - name: Build the Docker image
  #    run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
